apiVersion: v1
kind: ConfigMap
metadata:
  name: env-configmap
data:
  POSTGRES_HOST: mydbinstance.cxktdfjj88qn.us-east-1.rds.amazonaws.com
  POSTGRES_DB: postgres
  AWS_BUCKET: arn:aws:s3:::test-133750217366-dev
  AWS_REGION: us-east-1
  AWS_PROFILE: default
  JWT_SECRET: testing
  URL: http://localhost:8080